name       : gretl
version    : 2021c
release    : 21
source     :
    - http://prdownloads.sourceforge.net/gretl/gretl-2021c.tar.xz : be468b8233b2702a15df24d1efffdf44ce082c99617cbfa01d8e2fafda370f8a
license    : GPL-3.0-or-later
component  : office.maths
summary    : GNU regression, econometrics and time-series library
description: |
    Gretl (GNU regression, econometrics and time-series library) comprises libgretl, a shared library which provides various functions relating to econometric estimation, a command-line client program and a gui client, using GTK+.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lapack)
    - pkgconfig(libcurl)
    - pkgconfig(libR)
    - gnuplot
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-avx
build      : |
    %make
install    : |
    %make_install -j1
check      : |
    %make check
