name       : gretl
version    : 2017c
release    : 4
source     :
    - http://prdownloads.sourceforge.net/gretl/gretl-2017c.tar.xz : cba7ef3a094d98b50d991c67de443a5bc4dc75233af134c1f6a379fcdfeda846
license    : GPL-3.0
component  : office.maths
summary    : GNU regression, econometrics and time-series library
description: |
    Gretl (GNU regression, econometrics and time-series library) comprises libgretl, a shared library which provides various functions relating to econometric estimation, a command-line client program and a gui client, using GTK+.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libR)
    - gnuplot
    - openblas-devel
setup      : |
    %configure LAPACK_LIBS="-lopenblas" --disable-avx
build      : |
    %make
install    : |
    %make_install -j1
