name       : gretl
version    : 2020a
release    : 15
source     :
    - https://netix.dl.sourceforge.net/project/gretl/gretl/2020a/gretl-2020a.tar.xz : 4c369f33c9aa825920229263bfd12560168c4e46282240bee3497436a7ae9b7b
license    : GPL-3.0-or-later
component  : office.maths
summary    : GNU regression, econometrics and time-series library
description: |
    Gretl (GNU regression, econometrics and time-series library) comprises libgretl, a shared library which provides various functions relating to econometric estimation, a command-line client program and a gui client, using GTK+.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libR)
    - pkgconfig(openblas)
    - gnuplot
rundeps    :
    - gnuplot
setup      : |
    %configure LAPACK_LIBS="-lopenblas" --disable-avx
build      : |
    %make
install    : |
    %make_install -j1
check      : |
    %make check
