name       : gretl
version    : 2018a
release    : 7
source     :
    - https://netix.dl.sourceforge.net/project/gretl/gretl/2018a/gretl-2018a.tar.xz : f961fe48613cffd263bcb7ee3dff0bf5189d75b45a5cd03a062cfca381b455b7
license    : GPL-3.0-or-later
component  : office.maths
summary    : GNU regression, econometrics and time-series library
description: |
    Gretl (GNU regression, econometrics and time-series library) comprises libgretl, a shared library which provides various functions relating to econometric estimation, a command-line client program and a gui client, using GTK+.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libR)
    - pkgconfig(openblas)
    - gnuplot
rundeps    :
    - gnuplot
setup      : |
    %configure LAPACK_LIBS="-lopenblas" --disable-avx
build      : |
    %make
install    : |
    %make_install -j1
check      : |
    %make check
