name       : gretl
version    : 2016c
release    : 2
source     :
    - http://prdownloads.sourceforge.net/gretl/gretl-2016c.tar.xz : d27c22e06a7c59931b2b5a364eb846b7c7e5bf05d1260926baeed9455f2144e8
license    : GPL-3.0
component  : office.maths
summary    : GNU regression, econometrics and time-series library
description: |
    Gretl (GNU regression, econometrics and time-series library) comprises libgretl, a shared library which provides various functions relating to econometric estimation, a command-line client program and a gui client, using GTK+.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libR)
    - gnuplot
    - openblas-devel
setup      : |
    %configure LAPACK_LIBS="-lopenblas" --disable-avx
build      : |
    %make
install    : |
    %make_install -j1
